# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created: Fri Mar  1 09:29:04 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(800, 623)
        self.verticalLayout_9 = QtGui.QVBoxLayout(Settings)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_22 = QtGui.QLabel(Settings)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_9.addWidget(self.label_22)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cruiseControlBox = QtGui.QGroupBox(Settings)
        self.cruiseControlBox.setObjectName(_fromUtf8("cruiseControlBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.cruiseControlBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.cruiseControlBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.kpSlider = QtGui.QSlider(self.cruiseControlBox)
        self.kpSlider.setMaximum(10)
        self.kpSlider.setPageStep(1)
        self.kpSlider.setOrientation(QtCore.Qt.Vertical)
        self.kpSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.kpSlider.setObjectName(_fromUtf8("kpSlider"))
        self.verticalLayout.addWidget(self.kpSlider)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.kpLabel = QtGui.QLabel(self.cruiseControlBox)
        self.kpLabel.setObjectName(_fromUtf8("kpLabel"))
        self.horizontalLayout.addWidget(self.kpLabel)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.cruiseControlBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.kiSlider = QtGui.QSlider(self.cruiseControlBox)
        self.kiSlider.setMaximum(10)
        self.kiSlider.setPageStep(1)
        self.kiSlider.setOrientation(QtCore.Qt.Vertical)
        self.kiSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.kiSlider.setObjectName(_fromUtf8("kiSlider"))
        self.verticalLayout_2.addWidget(self.kiSlider)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.kiLabel = QtGui.QLabel(self.cruiseControlBox)
        self.kiLabel.setObjectName(_fromUtf8("kiLabel"))
        self.horizontalLayout.addWidget(self.kiLabel)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.cruiseControlBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.kdSlider = QtGui.QSlider(self.cruiseControlBox)
        self.kdSlider.setMaximum(10)
        self.kdSlider.setPageStep(1)
        self.kdSlider.setOrientation(QtCore.Qt.Vertical)
        self.kdSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.kdSlider.setObjectName(_fromUtf8("kdSlider"))
        self.verticalLayout_3.addWidget(self.kdSlider)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.kdLabel = QtGui.QLabel(self.cruiseControlBox)
        self.kdLabel.setObjectName(_fromUtf8("kdLabel"))
        self.horizontalLayout.addWidget(self.kdLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.cruiseControlBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.SP = QtGui.QSpinBox(self.cruiseControlBox)
        self.SP.setObjectName(_fromUtf8("SP"))
        self.horizontalLayout_2.addWidget(self.SP)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addWidget(self.cruiseControlBox)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_2 = QtGui.QGroupBox(Settings)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.compression_FD = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.compression_FD.setObjectName(_fromUtf8("compression_FD"))
        self.gridLayout.addWidget(self.compression_FD, 1, 1, 1, 1)
        self.compression_RP = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.compression_RP.setObjectName(_fromUtf8("compression_RP"))
        self.gridLayout.addWidget(self.compression_RP, 1, 4, 1, 1)
        self.damping_FD = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.damping_FD.setObjectName(_fromUtf8("damping_FD"))
        self.gridLayout.addWidget(self.damping_FD, 2, 1, 1, 1)
        self.compression_FP = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.compression_FP.setObjectName(_fromUtf8("compression_FP"))
        self.gridLayout.addWidget(self.compression_FP, 1, 2, 1, 1)
        self.damping_RD = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.damping_RD.setObjectName(_fromUtf8("damping_RD"))
        self.gridLayout.addWidget(self.damping_RD, 2, 3, 1, 1)
        self.damping_FP = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.damping_FP.setObjectName(_fromUtf8("damping_FP"))
        self.gridLayout.addWidget(self.damping_FP, 2, 2, 1, 1)
        self.compression_RD = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.compression_RD.setObjectName(_fromUtf8("compression_RD"))
        self.gridLayout.addWidget(self.compression_RD, 1, 3, 1, 1)
        self.damping_RP = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.damping_RP.setObjectName(_fromUtf8("damping_RP"))
        self.gridLayout.addWidget(self.damping_RP, 2, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.stiffness_FD = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.stiffness_FD.setObjectName(_fromUtf8("stiffness_FD"))
        self.gridLayout.addWidget(self.stiffness_FD, 3, 1, 1, 1)
        self.stiffness_FP = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.stiffness_FP.setObjectName(_fromUtf8("stiffness_FP"))
        self.gridLayout.addWidget(self.stiffness_FP, 3, 2, 1, 1)
        self.stiffness_RD = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.stiffness_RD.setObjectName(_fromUtf8("stiffness_RD"))
        self.gridLayout.addWidget(self.stiffness_RD, 3, 3, 1, 1)
        self.stiffness_RP = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.stiffness_RP.setObjectName(_fromUtf8("stiffness_RP"))
        self.gridLayout.addWidget(self.stiffness_RP, 3, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Settings)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.grip_FP = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.grip_FP.setObjectName(_fromUtf8("grip_FP"))
        self.gridLayout_2.addWidget(self.grip_FP, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 4, 1, 1)
        self.grip_RP = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.grip_RP.setObjectName(_fromUtf8("grip_RP"))
        self.gridLayout_2.addWidget(self.grip_RP, 1, 4, 1, 1)
        self.grip_FD = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.grip_FD.setObjectName(_fromUtf8("grip_FD"))
        self.gridLayout_2.addWidget(self.grip_FD, 1, 1, 1, 1)
        self.grip_RD = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.grip_RD.setObjectName(_fromUtf8("grip_RD"))
        self.gridLayout_2.addWidget(self.grip_RD, 1, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 3, 0, 1, 1)
        self.steerable_FD = QtGui.QCheckBox(self.groupBox_3)
        self.steerable_FD.setText(_fromUtf8(""))
        self.steerable_FD.setTristate(False)
        self.steerable_FD.setObjectName(_fromUtf8("steerable_FD"))
        self.gridLayout_2.addWidget(self.steerable_FD, 3, 1, 1, 1)
        self.steerable_FP = QtGui.QCheckBox(self.groupBox_3)
        self.steerable_FP.setText(_fromUtf8(""))
        self.steerable_FP.setObjectName(_fromUtf8("steerable_FP"))
        self.gridLayout_2.addWidget(self.steerable_FP, 3, 2, 1, 1)
        self.steerable_RD = QtGui.QCheckBox(self.groupBox_3)
        self.steerable_RD.setText(_fromUtf8(""))
        self.steerable_RD.setObjectName(_fromUtf8("steerable_RD"))
        self.gridLayout_2.addWidget(self.steerable_RD, 3, 3, 1, 1)
        self.steerable_RP = QtGui.QCheckBox(self.groupBox_3)
        self.steerable_RP.setText(_fromUtf8(""))
        self.steerable_RP.setObjectName(_fromUtf8("steerable_RP"))
        self.gridLayout_2.addWidget(self.steerable_RP, 3, 4, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 2, 0, 1, 1)
        self.rollInfluence_FD = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.rollInfluence_FD.setObjectName(_fromUtf8("rollInfluence_FD"))
        self.gridLayout_2.addWidget(self.rollInfluence_FD, 2, 1, 1, 1)
        self.rollInfluence_FP = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.rollInfluence_FP.setObjectName(_fromUtf8("rollInfluence_FP"))
        self.gridLayout_2.addWidget(self.rollInfluence_FP, 2, 2, 1, 1)
        self.rollInfluence_RD = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.rollInfluence_RD.setObjectName(_fromUtf8("rollInfluence_RD"))
        self.gridLayout_2.addWidget(self.rollInfluence_RD, 2, 3, 1, 1)
        self.rollInfluence_RP = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.rollInfluence_RP.setObjectName(_fromUtf8("rollInfluence_RP"))
        self.gridLayout_2.addWidget(self.rollInfluence_RP, 2, 4, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(Settings)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.timeEdit = QtGui.QTimeEdit(self.groupBox_4)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.timeEdit)
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.dial = QtGui.QDial(self.groupBox_4)
        self.dial.setMinimum(0)
        self.dial.setMaximum(100)
        self.dial.setProperty("value", 0)
        self.dial.setSliderPosition(0)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.horizontalLayout_5.addWidget(self.dial)
        self.graphicsView = QtGui.QGraphicsView(self.groupBox_4)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout_5.addWidget(self.graphicsView)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.resetButton = QtGui.QPushButton(Settings)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.saveButton = QtGui.QPushButton(Settings)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Settings)
        QtCore.QObject.connect(self.kpSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.kpLabel.setNum)
        QtCore.QObject.connect(self.kiSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.kiLabel.setNum)
        QtCore.QObject.connect(self.kdSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.kdLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "Form", None))
        self.label_22.setText(_translate("Settings", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">Global Settings</span></p></body></html>", None))
        self.cruiseControlBox.setTitle(_translate("Settings", "Cruise Control", None))
        self.label.setText(_translate("Settings", "Kp", None))
        self.kpLabel.setText(_translate("Settings", "0", None))
        self.label_2.setText(_translate("Settings", "Ki", None))
        self.kiLabel.setText(_translate("Settings", "0", None))
        self.label_3.setText(_translate("Settings", "Kd", None))
        self.kdLabel.setText(_translate("Settings", "0", None))
        self.label_4.setText(_translate("Settings", "Set Point:", None))
        self.groupBox_2.setTitle(_translate("Settings", "Suspension", None))
        self.label_5.setText(_translate("Settings", "compression:", None))
        self.label_6.setText(_translate("Settings", "damping:", None))
        self.label_7.setText(_translate("Settings", "<html><head/><body><p><span style=\" font-weight:600;\">Front Driver</span></p></body></html>", None))
        self.label_8.setText(_translate("Settings", "<b>Front Pass.</b>", None))
        self.label_10.setText(_translate("Settings", "<b>Rear Driver</b>", None))
        self.label_11.setText(_translate("Settings", "<b>Rear Pass.</b>", None))
        self.label_12.setText(_translate("Settings", "stiffness:", None))
        self.groupBox_3.setTitle(_translate("Settings", "Tires", None))
        self.label_17.setText(_translate("Settings", "<b>Rear Pass.</b>", None))
        self.label_18.setText(_translate("Settings", "Grip:", None))
        self.label_15.setText(_translate("Settings", "<b>Front Pass.</b>", None))
        self.label_16.setText(_translate("Settings", "<b>Rear Driver</b>", None))
        self.label_14.setText(_translate("Settings", "<b>Front Driver</b>", None))
        self.label_19.setText(_translate("Settings", "Steerable:", None))
        self.label_23.setText(_translate("Settings", "Roll influence:", None))
        self.groupBox_4.setTitle(_translate("Settings", "Game", None))
        self.label_20.setText(_translate("Settings", "Time Limit:", None))
        self.timeEdit.setDisplayFormat(_translate("Settings", "mm:ss", None))
        self.label_21.setText(_translate("Settings", "Tilt Threshold:", None))
        self.resetButton.setText(_translate("Settings", "Load Factory Defaults", None))
        self.saveButton.setText(_translate("Settings", "Save", None))

